"""
carol_portfolio_listener.py
============================
Carol's side of the 3-party encrypted portfolio risk pipeline.

Carol holds ONLY the polynomial model JSONs — never the secret key,
never the plaintext weights. She evaluates P_risk(w) and P_return(w)
using only additions and multiplications, which are the two operations
CKKS supports natively.

Carol exposes four entry points matching Alice's four pipeline modes:

    carol_evaluate_classical(w, sigma, mu)
        → Plaintext evaluation of exact quadratic σ²=w⊤Σw (classical baseline)

    carol_evaluate_quantum(z, qt_risk_poly, qt_ret_poly)
        → Plaintext evaluation of VQC degree-2 surrogates

    carol_evaluate_classical_encrypted(enc_z_bytes, pub_ctx_bytes, cl_poly)
        → CKKS evaluation of classical polynomial on encrypted weights

    carol_evaluate_quantum_encrypted(enc_z_bytes, pub_ctx_bytes, risk_poly, ret_poly)
        → CKKS evaluation of both VQC surrogates on encrypted weights
          Returns two ciphertexts: Enc(P_risk), Enc(P_return)

Design notes
------------
• Carol never calls .decrypt() — she has no secret key.
• All encrypted operations are: add_plain, mul_plain, mul (enc×enc),
  and add (enc+enc). No non-polynomial ops are used.
• Degree-2 polynomial: 1 multiplication level consumed (diagonal +
  off-diagonal quadratic terms). Stays within the 4-level CKKS budget.
• Off-diagonal quadratic terms Enc(z_i) * Enc(z_j) use relinearization
  keys (generated by Alice and passed in the public context).

Dependencies
------------
    pip install tenseal numpy
"""

import json
import warnings
from typing import Tuple

import numpy as np

try:
    import tenseal as ts
    TENSEAL_AVAILABLE = True
except ImportError:
    TENSEAL_AVAILABLE = False
    warnings.warn(
        "TenSEAL not installed — encrypted Carol modes unavailable.\n"
        "  pip install tenseal",
        RuntimeWarning,
    )


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _load_poly(poly: dict) -> Tuple[float, np.ndarray, np.ndarray]:
    """Unpack polynomial JSON into (bias, linear_vec, quadratic_matrix)."""
    bias = float(poly["bias"])
    a    = np.array(poly["linear"],    dtype=np.float64)
    Q    = np.array(poly["quadratic"], dtype=np.float64)
    return bias, a, Q


def _deserialize_enc_vector(enc_bytes: bytes,
                              pub_ctx_bytes: bytes) -> "ts.CKKSVector":
    """Reconstruct an encrypted CKKSVector from serialised bytes."""
    ctx = ts.context_from(pub_ctx_bytes)
    enc = ts.lazy_ckks_vector_from(enc_bytes)
    enc.link_context(ctx)
    return enc, ctx


# ─────────────────────────────────────────────────────────────────────────────
# MODE 1  —  CLASSICAL PLAINTEXT
# Carol evaluates exact quadratic w⊤Σw in plaintext.
# This is the reference: no surrogate, no encryption.
# ─────────────────────────────────────────────────────────────────────────────

def carol_evaluate_classical(w: np.ndarray,
                              sigma: np.ndarray,
                              mu: np.ndarray) -> dict:
    """
    Plaintext evaluation of the classical risk model.

    Parameters
    ----------
    w     : portfolio weight vector (N,)
    sigma : covariance matrix (N, N)
    mu    : expected returns (N,)

    Returns
    -------
    dict with variance, portfolio_return, and sharpe components
    """
    variance         = float(w @ sigma @ w)
    portfolio_return = float(w @ mu)

    print(f"[CAROL] Classical plaintext → variance={variance:.6f}  "
          f"μ_p={portfolio_return:.6f}")

    return {
        "variance":         variance,
        "portfolio_return":  portfolio_return,
        "mode":             "classical_plaintext",
    }


# ─────────────────────────────────────────────────────────────────────────────
# MODE 2  —  QUANTUM PLAINTEXT
# Carol evaluates VQC degree-2 surrogates in plaintext.
# Isolates the quantum model's effect without FHE overhead.
# ─────────────────────────────────────────────────────────────────────────────

def carol_evaluate_quantum(z: np.ndarray,
                            qt_risk_poly: dict,
                            qt_ret_poly: dict) -> dict:
    """
    Plaintext evaluation of both VQC polynomial surrogates.

    Parameters
    ----------
    z           : standardized feature vector (the weights after scaler.transform)
    qt_risk_poly: polynomial JSON for P_risk  (fit to VQC volatility/ES output)
    qt_ret_poly : polynomial JSON for P_return (fit to VQC return output)

    Returns
    -------
    dict with P_risk and P_return scores
    """
    bias_r, a_r, Q_r = _load_poly(qt_risk_poly)
    bias_p, a_p, Q_p = _load_poly(qt_ret_poly)

    # f̂(z) = bias + a⊤z + z⊤Qz
    p_risk   = bias_r + float(a_r @ z) + float(z @ Q_r @ z)
    p_return = bias_p + float(a_p @ z) + float(z @ Q_p @ z)

    print(f"[CAROL] Quantum plaintext → P_risk={p_risk:.6f}  P_return={p_return:.6f}")

    return {
        "P_risk":   p_risk,
        "P_return": p_return,
        "mode":     "quantum_plaintext",
    }


# ─────────────────────────────────────────────────────────────────────────────
# ENCRYPTED POLYNOMIAL EVALUATION  (shared core)
# ─────────────────────────────────────────────────────────────────────────────

def _evaluate_poly_encrypted(enc_z: "ts.CKKSVector",
                              ctx: "ts.Context",
                              poly: dict) -> "ts.CKKSVector":
    """
    Evaluate a degree-2 polynomial on an encrypted vector.

    f̂(z) = bias + Σ_i a_i·z_i + Σ_{i,j} Q_ij·z_i·z_j

    All operations are CKKS-legal (add_plain, mul_plain, mul, add).
    Carol never decrypts — she works entirely in ciphertext.

    Multiplicative depth used: 1 level (for z_i * z_j).
    This leaves 3 levels remaining from the 4-level CKKS budget,
    which is sufficient for Chebyshev sqrt if applied afterwards.

    Parameters
    ----------
    enc_z : CKKSVector of standardized weights, encrypted by Alice
    ctx   : public CKKS context (no secret key)
    poly  : dict with keys 'bias', 'linear' (list), 'quadratic' (list of lists)

    Returns
    -------
    enc_score : CKKSVector holding Enc(f̂(z)) — single encrypted value
    """
    bias, a, Q = _load_poly(poly)
    n = len(a)

    # ── Validate dimensions ───────────────────────────────────────────────────
    if Q.shape != (n, n):
        raise ValueError(
            f"Polynomial quadratic matrix shape {Q.shape} "
            f"doesn't match linear dim {n}."
        )

    # ── Step 1: Start accumulator at bias (plaintext scalar) ─────────────────
    # We build enc_score as a CKKSVector of length 1 holding the running sum.
    # Initialise by encrypting [bias] — or add it as a plain scalar below.
    enc_score = ts.ckks_vector(ctx, [bias])

    # ── Step 2: Extract individual encrypted scalar slots ────────────────────
    # enc_z holds [z_0, z_1, ..., z_{n-1}] in a single ciphertext.
    # We extract each z_i as its own ciphertext by masking with a plain vector.
    # mask_i = [0, ..., 1, ..., 0] with 1 at position i.
    enc_z_scalars = []
    for i in range(n):
        mask = [1.0 if j == i else 0.0 for j in range(n)]
        enc_zi = enc_z * mask          # element-wise mul with plaintext mask
        # Sum all slots → single value (dot with all-ones vector of length n)
        ones   = [1.0] * n
        enc_zi_scalar = enc_zi.dot(ones)   # Enc(z_i) as scalar ciphertext
        enc_z_scalars.append(enc_zi_scalar)

    # ── Step 3: Linear terms  Σ a_i · Enc(z_i) ───────────────────────────────
    for i in range(n):
        if abs(float(a[i])) < 1e-12:
            continue   # skip zero coefficients
        linear_term = enc_z_scalars[i] * float(a[i])   # scalar mul (no depth)
        enc_score   = enc_score + linear_term

    # ── Step 4: Quadratic terms  Σ_{i,j} Q_ij · Enc(z_i) · Enc(z_j) ─────────
    # Diagonal terms: Q_ii · z_i² — 1 multiplication level
    # Off-diagonal:   Q_ij · z_i · z_j — same 1 level (but separate mul)
    # We process upper triangle + diagonal to avoid double-counting.
    for i in range(n):
        for j in range(i, n):
            q_ij = float(Q[i, j])
            if i != j:
                # Symmetrize: Q_ij + Q_ji (surrogate may not be symmetric)
                q_ij += float(Q[j, i])
            if abs(q_ij) < 1e-12:
                continue

            # Enc(z_i) * Enc(z_j) — consumes 1 multiplicative level
            enc_zizj = enc_z_scalars[i] * enc_z_scalars[j]
            quad_term = enc_zizj * q_ij   # plain scalar mul (no extra level)
            enc_score  = enc_score + quad_term

    return enc_score


# ─────────────────────────────────────────────────────────────────────────────
# MODE 3  —  CLASSICAL ENCRYPTED
# Carol evaluates w⊤Σw polynomial under CKKS.
# ─────────────────────────────────────────────────────────────────────────────

def carol_evaluate_classical_encrypted(enc_z_bytes: bytes,
                                        pub_ctx_bytes: bytes,
                                        cl_poly: dict) -> bytes:
    """
    CKKS evaluation of the classical variance polynomial.

    Carol receives Enc(z) and the public context from Alice.
    She evaluates the polynomial and returns Enc(variance) — serialised bytes.

    Parameters
    ----------
    enc_z_bytes   : serialised CKKSVector of Alice's encrypted weights
    pub_ctx_bytes : serialised public CKKS context (no secret key)
    cl_poly       : classical polynomial JSON  (bias, linear, quadratic for w⊤Σw)

    Returns
    -------
    bytes : serialised Enc(variance) to send back to Alice
    """
    if not TENSEAL_AVAILABLE:
        raise RuntimeError("TenSEAL not available on Carol's side.")

    enc_z, ctx = _deserialize_enc_vector(enc_z_bytes, pub_ctx_bytes)
    print(f"[CAROL] Received Enc(z) for classical encrypted evaluation.")

    enc_variance = _evaluate_poly_encrypted(enc_z, ctx, cl_poly)
    print(f"[CAROL] Polynomial evaluated in ciphertext — returning Enc(variance).")

    return enc_variance.serialize()


# ─────────────────────────────────────────────────────────────────────────────
# MODE 4  —  QUANTUM ENCRYPTED  (full pipeline)
# Carol evaluates BOTH P_risk and P_return under CKKS.
# ─────────────────────────────────────────────────────────────────────────────

def carol_evaluate_quantum_encrypted(enc_z_bytes: bytes,
                                      pub_ctx_bytes: bytes,
                                      qt_risk_poly: dict,
                                      qt_ret_poly: dict) -> Tuple[bytes, bytes]:
    """
    CKKS evaluation of both VQC polynomial surrogates.

    Carol evaluates P_risk(w) and P_return(w) entirely in ciphertext.
    She returns two serialised ciphertexts to Alice.
    Carol never decrypts either result.

    Parameters
    ----------
    enc_z_bytes   : serialised CKKSVector of Alice's encrypted weights
    pub_ctx_bytes : serialised public CKKS context (no secret key)
    qt_risk_poly  : JSON polynomial model for P_risk
    qt_ret_poly   : JSON polynomial model for P_return

    Returns
    -------
    (enc_risk_bytes, enc_ret_bytes) : serialised ciphertexts for both scores
    """
    if not TENSEAL_AVAILABLE:
        raise RuntimeError("TenSEAL not available on Carol's side.")

    enc_z, ctx = _deserialize_enc_vector(enc_z_bytes, pub_ctx_bytes)
    print(f"[CAROL] Received Enc(z) for quantum encrypted evaluation.")

    # Evaluate P_risk polynomial in ciphertext
    print(f"[CAROL] Evaluating Enc(P_risk)...")
    enc_risk = _evaluate_poly_encrypted(enc_z, ctx, qt_risk_poly)

    # Evaluate P_return polynomial in ciphertext
    # Note: enc_z must be re-deserialised for the second evaluation because
    # the first evaluation consumed multiplicative levels in-place.
    enc_z2, _ = _deserialize_enc_vector(enc_z_bytes, pub_ctx_bytes)
    print(f"[CAROL] Evaluating Enc(P_return)...")
    enc_ret  = _evaluate_poly_encrypted(enc_z2, ctx, qt_ret_poly)

    print(f"[CAROL] Both surrogates evaluated — returning Enc(P_risk), Enc(P_return).")
    return enc_risk.serialize(), enc_ret.serialize()


# ─────────────────────────────────────────────────────────────────────────────
# STANDALONE TEST  (run directly to verify Carol works without Alice)
# ─────────────────────────────────────────────────────────────────────────────

def _self_test():
    """
    Quick smoke test: build a toy polynomial, encrypt a weight vector,
    evaluate on Carol's side, decrypt, and compare against plaintext result.
    Requires TenSEAL.
    """
    if not TENSEAL_AVAILABLE:
        print("[CAROL SELF-TEST] TenSEAL not available — skipping encrypted test.")
        _self_test_plaintext_only()
        return

    print("[CAROL SELF-TEST] Running encrypted polynomial evaluation test...")

    # Build a small toy polynomial (n=4 features, matches fraud project dim)
    n    = 4
    rng  = np.random.default_rng(42)
    bias = 0.05
    a    = rng.uniform(-0.1, 0.1, n)
    Q    = rng.uniform(-0.05, 0.05, (n, n))
    Q    = (Q + Q.T) / 2   # symmetrize
    poly = {"bias": bias, "linear": a.tolist(), "quadratic": Q.tolist()}

    # Ground-truth plaintext evaluation
    z          = rng.uniform(-1, 1, n)
    expected   = bias + float(a @ z) + float(z @ Q @ z)

    # Build Alice's context
    ctx = ts.context(
        ts.SCHEME_TYPE.CKKS,
        poly_modulus_degree=16384,
        coeff_mod_bit_sizes=[60, 40, 40, 40, 60],
    )
    ctx.generate_galois_keys()
    ctx.generate_relin_keys()
    ctx.global_scale = 2 ** 40

    # Alice encrypts
    enc_z        = ts.ckks_vector(ctx, z.tolist())
    enc_z_bytes  = enc_z.serialize()
    pub_ctx_bytes = ctx.serialize(save_secret_key=False)

    # Carol evaluates (classical encrypted mode as proxy)
    enc_score_bytes = carol_evaluate_classical_encrypted(
        enc_z_bytes, pub_ctx_bytes, poly
    )

    # Alice decrypts
    enc_score = ts.lazy_ckks_vector_from(enc_score_bytes)
    enc_score.link_context(ctx)
    result = float(enc_score.decrypt()[0])

    print(f"[CAROL SELF-TEST] Expected  : {expected:.8f}")
    print(f"[CAROL SELF-TEST] Encrypted : {result:.8f}")
    print(f"[CAROL SELF-TEST] Error     : {abs(result - expected):.2e}")

    if abs(result - expected) < 1e-3:
        print("[CAROL SELF-TEST] ✓ PASSED — encrypted evaluation matches plaintext.")
    else:
        print("[CAROL SELF-TEST] ✗ FAILED — check CKKS parameters / polynomial coeffs.")


def _self_test_plaintext_only():
    """Fallback test without TenSEAL."""
    print("[CAROL SELF-TEST] Running plaintext-only test...")
    n   = 4
    rng = np.random.default_rng(42)
    w   = rng.dirichlet(np.ones(n))   # valid simplex weights
    sigma = rng.uniform(0, 0.01, (n, n))
    sigma = sigma @ sigma.T            # make positive semidefinite
    mu    = rng.uniform(0.0001, 0.001, n)

    result = carol_evaluate_classical(w, sigma, mu)
    expected_var = float(w @ sigma @ w)

    print(f"[CAROL SELF-TEST] variance expected : {expected_var:.8f}")
    print(f"[CAROL SELF-TEST] variance from Carol: {result['variance']:.8f}")

    if abs(result["variance"] - expected_var) < 1e-10:
        print("[CAROL SELF-TEST] ✓ PASSED — plaintext variance matches.")
    else:
        print("[CAROL SELF-TEST] ✗ FAILED.")


if __name__ == "__main__":
    _self_test()